In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

%matplotlib inline

In [2]:
loans = pd.read_csv("/home/terrence/Projects/PycharmProjects/MachineLeaningTut/data/lending_club_data01.csv")
loans.head()

int_rate  installment  open_acc  revol_bal  revol_util  total_acc  \
0     10.65       162.87         3      13648        83.7          9   
1     15.27        59.83         3       1687         9.4          4   
2     15.96        84.33         2       2956        98.5         10   
3     13.49       339.31        10       5598        21.0         37   
4      7.90       156.46         9       7963        28.3         12   

   bad_loans  grade_num  
0          0          5  
1          1          4  
2          0          4  
3          0          4  
4          0          6

In [3]:
loans['good_loans'] = loans['bad_loans'].apply(lambda y: 'yes' if y==0 else 'no')
loans.head()

int_rate  installment  open_acc  revol_bal  revol_util  total_acc  \
0     10.65       162.87         3      13648        83.7          9   
1     15.27        59.83         3       1687         9.4          4   
2     15.96        84.33         2       2956        98.5         10   
3     13.49       339.31        10       5598        21.0         37   
4      7.90       156.46         9       7963        28.3         12   

   bad_loans  grade_num good_loans  
0          0          5        yes  
1          1          4         no  
2          0          4        yes  
3          0          4        yes  
4          0          6        yes

In [4]:
loans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1468 entries, 0 to 1467
Data columns (total 9 columns):
int_rate       1468 non-null float64
installment    1468 non-null float64
open_acc       1468 non-null int64
revol_bal      1468 non-null int64
revol_util     1468 non-null float64
total_acc      1468 non-null int64
bad_loans      1468 non-null int64
grade_num      1468 non-null int64
good_loans     1468 non-null object
dtypes: float64(3), int64(5), object(1)
memory usage: 103.3+ KB


In [16]:
X = loans.drop(['bad_loans', 'good_loans'], axis=1)
y = loans['good_loans']
print (X.shape, y.shape)

(1468, 7) (1468,)


In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [21]:
prediction = model.predict(X_test)
print(confusion_matrix(y_test, prediction))

[[ 16  38]
 [ 43 197]]


In [22]:
print(classification_report(y_test, prediction))

              precision    recall  f1-score   support

          no       0.27      0.30      0.28        54
         yes       0.84      0.82      0.83       240

    accuracy                           0.72       294
   macro avg       0.55      0.56      0.56       294
weighted avg       0.73      0.72      0.73       294



In [2]:
rf_model = RandomForestClassifier(n_estimators=150)
rf_model.fit(X_train, y_train)

NameError: name 'X_train' is not defined

In [25]:
rf_prediction = rf_model.predict(X_test)
print(classification_report(y_test, rf_prediction))

              precision    recall  f1-score   support

          no       0.22      0.04      0.06        54
         yes       0.82      0.97      0.89       240

    accuracy                           0.80       294
   macro avg       0.52      0.50      0.48       294
weighted avg       0.71      0.80      0.74       294



In [26]:
print(confusion_matrix(y_test, rf_prediction))


[[  2  52]
 [  7 233]]


In [3]:
loans = pd.read_csv("/home/terrence/Projects/PycharmProjects/MachineLeaningTut/data/lending_club_new_data.csv")
loans.head()

loan_amnt  funded_amnt  funded_amnt_inv  int_rate  installment  annual_inc  \
0       5000         5000             4975     10.65       162.87       24000   
1       2500         2500             2500     15.27        59.83       30000   
2       2400         2400             2400     15.96        84.33       12252   
3      10000        10000            10000     13.49       339.31       49200   
4       5000         5000             5000      7.90       156.46       36000   

     dti  delinq_2yrs  inq_last_6mths  open_acc  ...  total_rec_late_fee  \
0  27.65            0               1         3  ...                0.00   
1   1.00            0               5         3  ...                0.00   
2   8.72            0               2         2  ...                0.00   
3  20.00            0               1        10  ...               16.97   
4  11.20            0               3         9  ...                0.00   

   recoveries  collection_recovery_fee  last_pymnt_amnt  bad_loans  \
0        0.00                     0.00           171.62          0   
1      117.08                     1.11           119.66          1   
2        0.00                     0.00           649.91          0   
3        0.00                     0.00           357.48          0   
4        0.00                     0.00           161.03          0   

   emp_length_num  grade_num  sub_grade_num  delinq_2yrs_zero  \
0              11          5            0.4                 1   
1               1          4            0.8                 1   
2              11          4            1.0                 1   
3              11          4            0.2                 1   
4               4          6            0.8                 1   

   payment_inc_ratio  
0            8.14350  
1            2.39320  
2            8.25955  
3            8.27585  
4            5.21533  

[5 rows x 24 columns]

In [4]:
loans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9516 entries, 0 to 9515
Data columns (total 24 columns):
loan_amnt                  9516 non-null int64
funded_amnt                9516 non-null int64
funded_amnt_inv            9516 non-null int64
int_rate                   9516 non-null float64
installment                9516 non-null float64
annual_inc                 9516 non-null int64
dti                        9516 non-null float64
delinq_2yrs                9516 non-null int64
inq_last_6mths             9516 non-null int64
open_acc                   9516 non-null int64
total_pymnt                9516 non-null float64
total_pymnt_inv            9516 non-null float64
total_rec_prncp            9516 non-null float64
total_rec_int              9516 non-null float64
total_rec_late_fee         9516 non-null float64
recoveries                 9516 non-null float64
collection_recovery_fee    9516 non-null float64
last_pymnt_amnt            9516 non-null float64
bad_loans                

In [6]:
loans['good_loans'] = loans['bad_loans'].apply(lambda y: 'yes' if y==0 else 'no')
X = loans.drop(['bad_loans', 'good_loans'], axis=1)
y = loans['good_loans']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

model = DecisionTreeClassifier()
model.fit(X_train, y_train)
prediction = model.predict(X_test)
print(confusion_matrix(y_test, prediction))
print(classification_report(y_test, prediction))


[[ 313    9]
 [   5 1577]]
              precision    recall  f1-score   support

          no       0.98      0.97      0.98       322
         yes       0.99      1.00      1.00      1582

    accuracy                           0.99      1904
   macro avg       0.99      0.98      0.99      1904
weighted avg       0.99      0.99      0.99      1904



In [7]:
rf_model = RandomForestClassifier(n_estimators=150)
rf_model.fit(X_train, y_train)
rf_prediction = rf_model.predict(X_test)
print(classification_report(y_test, rf_prediction))
print(confusion_matrix(y_test, rf_prediction))



              precision    recall  f1-score   support

          no       1.00      0.97      0.98       322
         yes       0.99      1.00      1.00      1582

    accuracy                           0.99      1904
   macro avg       1.00      0.98      0.99      1904
weighted avg       0.99      0.99      0.99      1904

[[ 312   10]
 [   0 1582]]
